### PR TITLE
Changed nom version to v5.

### PR DESCRIPTION
**Pull request by pJunger**
I saw that dependabot failed to upgrade the nom version to v5, so I took the liberty to do it manually.
As some things like the message macros were removed, one thing lead to another and now it's completely macro free.

One caveat though: The regex function is merged, but not officially released, so before merging this, there needs to be another nom release (before v6 is out...).
Unfortunately I didn't manage to leave the re_bytes_find macros in ...

### CODE REVIEW

**Comment by saschagrunert** [comment]
That’s a very nice contribution, many thanks for that! We could also stick to a non released nom version in the meanwhile if that helps.

**Comment by pJunger** [comment]
As you'd like - I also can see that I won't let it get stale until the nom version 5.1.2 is released.
But if you want to merge it, should we specify a specific revision then?

**Comment by saschagrunert** [comment]
Let’s specify the master and let dependabot update it regularly. This should be handled via Cargo.lock. If the next release gets out, we can pin it back to an official nom version. :)

**Comment by pJunger** [comment]
Right, I forgot about the lock file - I'll remove the `draft` tag then.
I somehow pushed a lot of crap - removed it again.
Diff should be a lot smaller now, too.

**Comment by saschagrunert** [comment]
LGTM, thanks!

**Pull request merged**
